LearningCenter.App/Areas/Forum/Controllers/ForumController.cs
namespace LearningCenter.App.Areas.Forum.Controllers
{
    using System.Net;
    using System.Web.Mvc;
    using LearningCenter.App.Extensions;
    using LearningCenter.Models.BindingModels.Forum;
    using LearningCenter.Models.ViewModels.Forum;
    using LearningCenter.Services.Interfaces;
    using Microsoft.AspNet.Identity;
    using PagedList;
    

    [RouteArea("forum")]
    public class ForumController : Controller
    {
        private IForumService service;

        public ForumController(IForumService service)
        {
            this.service = service;
        }
        
        [HttpGet]
        [AllowAnonymous]
        [Route]
        public ActionResult All()
        {
            ForumListViewModel viewModel = this.service.GetForumListViewModel();
            return this.View(viewModel);
        }
        
        [HttpGet]
        [OutputCache(Duration = 3)]
        public PartialViewResult Display(string search, int? page)
        {
            this.ViewBag.SearchKeyWord = search;

            var viewModels = this.service.SearchTopics(search);
            return this.PartialView("_DisplayTopics", viewModels.ToPagedList(page ?? 1, 10));
        }
        

        [HttpGet]
        [AllowAnonymous]
        [Route("topic/{id:int:min(1)}")]
        public ActionResult Detailed(int id)
        {
            if (id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            this.ViewBag.TopicId = id;
            DetailedTopicViewModel viewModel =  this.service.DetailedTopic(id);
            
            return this.View(viewModel);
        }

        [HttpGet]
        [CustomAuthorize(Roles = "User,Admin,Instructor")]
        [Route("add")]
        public ActionResult Add()
        {
            return this.View(new AddTopicViewModel());
        }

        [HttpPost]
        [CustomAuthorize(Roles = "User,Admin,Instructor")]
        [Route("add")]
        public ActionResult Add([Bind(Include = "Title,Content,Tags")] AddTopicBindingModel model)
        {
            if (this.ModelState.IsValid)
            {
                if (this.User == null)
                {
                return this.RedirectToAction("All");
                }
                string userId = this.User.Identity.GetUserId();
                this.service.AddTopic(model, userId);
                return this.RedirectToAction("All");
            }
            return this.View(this.service.GetAddTopicViewModel(model));
        }

        [HttpGet]
        [CustomAuthorize(Roles = "User,Admin,Instructor")]
        [Route("edit/{id:int:min(1)}")]
        public ActionResult EditTopic(int id)
        {
            if (id < 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EditTopicViewModel viewModel = this.service.GetEditViewModel(id);
            
            return this.View(viewModel);
        }

        [HttpPost]
        [CustomAuthorize(Roles = "User,Admin,Instructor")]
        [Route("edit/{id:int:min(1)}")]
        public ActionResult EditTopic([Bind(Include = "Id,Content,Tags")] EditTopicBindingModel model)
        {
            if (this.ModelState.IsValid)
            {
                this.service.EditTopic(model);
                return this.RedirectToAction("Detailed", new { id = model.Id });
            }

            return this.View(this.service.GetEditViewModel(model.Id));
        }

        
        [HttpGet]
        [CustomAuthorize(Roles = "User,Admin,Instructor")]
        public ActionResult AddReply()
        {
            return this.PartialView("_AddReply");
        }

        [HttpPost]
        [CustomAuthorize(Roles = "User,Admin,Instructor")]
        public ActionResult AddReply([Bind(Include = "TopicId,Content")] AddReplyBindingModel model)
        {
            if (this.ModelState.IsValid)
            {
                string userId = User.Identity.GetUserId();
                this.service.AddReply(model, userId);

                return this.RedirectToAction("Detailed", new { id = model.TopicId });
            }
            return this.PartialView("_AddReply");
        }
    }
}

LearningCenter.App/Controllers/CoursesController.cs
namespace LearningCenter.App.Controllers
{
    using System.Data.Entity;
    using System.Net;
    using System.Web.Mvc;
    using LearningCenter.Data;
    using LearningCenter.Models.EntityModels;
    using LearningCenter.Services.Interfaces;

    [Authorize(Roles = "Admin,User")]
    [RoutePrefix("courses")]
    public class CoursesController : Controller
    {
        private LearningCenterContext db = new LearningCenterContext();
        private ICourseService service;

        public CoursesController(ICourseService service)
        {
            this.service = service;
        }

        // GET: Courses
        [HttpGet]
        [AllowAnonymous]
        [Route]
        public ActionResult All()
        {
            var courses = this.service.GetAllCourses();
            return View(courses);
        }

        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Courses/Create
        public ActionResult Create()
        {
            ViewBag.QuizId = new SelectList(db.Units, "Id", "Title");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Description,QuizId")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("All");
            }

            ViewBag.QuizId = new SelectList(db.Units, "Id", "Title", course.QuizId);
            return View(course);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            ViewBag.QuizId = new SelectList(db.Units, "Id", "Title", course.QuizId);
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Description,QuizId")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("All");
            }
            ViewBag.QuizId = new SelectList(db.Units, "Id", "Title", course.QuizId);
            return View(course);
        }

        // GET: Courses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("All");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LearningCenter.App/Controllers/UsersController.cs
namespace LearningCenter.App.Controllers
{
    using System.Net;
    using System.Web.Mvc;
    using LearningCenter.Models.BindingModels.User;
    using LearningCenter.Models.ViewModels.User;
    using LearningCenter.Services.Interfaces;
    using Microsoft.AspNet.Identity;

    [Authorize]
    [RoutePrefix("users")]
    public class UsersController : Controller
    {
        private IUserService service;

        public UsersController(IUserService service)
        {
            this.service = service;
        }

        [HttpGet]
        [Route("profile/{username}")]
        public ActionResult ProfilePage(string username)
        {
            if (string.IsNullOrEmpty(username))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProfileViewModel viewModel = this.service.GetProfileViewModel(username);
            if (viewModel == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            return this.View(viewModel);
        }

        [HttpGet]
        [Route("edit/{username}")]
        public ActionResult Edit(string username)
        {
            if (string.IsNullOrEmpty(username))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!User.Identity.Name.StartsWith(username))
            {
                return this.RedirectToAction("ProfilePage", new {username = username.ToLower()});
            }
            EditProfileViewModel viewModel = this.service.GetEditProfileViewModel(username);
            if (viewModel == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            return this.View(viewModel);
        }

        [HttpPost]
        [Route("edit/{username}")]
        public ActionResult Edit([Bind(Include = "FirstName,LastName")]EditProfileBindingModel model)
        {
            string userId = User.Identity.GetUserId();

            var indexOfAt = User.Identity.Name.IndexOf("@");
            var currentUsername = User.Identity.Name.Substring(0, indexOfAt);

            if (this.ModelState.IsValid)
            {
                this.service.EditProfile(model, userId);
                return this.RedirectToAction("ProfilePage", new {username = currentUsername});
            }
            EditProfileViewModel viewModel = this.service.GetEditProfileViewModel(currentUsername);
            if (viewModel == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            return this.View(viewModel);
        }
        
        }
}

LearningCenter.App/Views/Users/All.cshtml
@using LearningCenter.Models.ViewModels.Admin
@model IEnumerable<AllUserViewModel>
@{
    ViewBag.Title = "Users";
}

<div class="row">
    <div class="col-sm-12">
        <h2 class="heading-centered">Users</h2>
    </div>
</div>
<div class="row">
    <form class="form-horizontal" method="get">
        <div class="col-sm-8 col-sm-offset-1">
            <div class="form-group">
                <input type="text" class="form-control" name="parameter" placeholder="Search for user" />
            </div>
        </div>
        <div class="col-sm-1">
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>

<table class="table table-striped table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Roles)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EnrolledCourses)
        </th>
    </tr>
    @foreach (var item in Model)
    {
        var indexOfAt = item.Email.IndexOf("@");
        var currentUsername = User.Identity.Name.Substring(0, indexOfAt);
        <tr>
            <td>
                @Html.ActionLink(item.Email, "ProfilePage", "Users", new { username = currentUsername })
            </td>
            <td>
                @Html.DisplayFor(model => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(model => item.LastName)
            </td>
            <td>
                @foreach (var role in item.Roles)
                {
                    <p>@role</p>
                }
            </td>
            <td>
                @Html.DisplayFor(model => item.EnrolledCourses)
            </td>
        </tr>
    }
</table>

LearningCenter.App/Views/Users/Edit.cshtml
@using LearningCenter.Models.ViewModels.User
@model EditProfileViewModel

@{
    ViewBag.Title = "Edit Profile";
    var indexOfAt = User.Identity.Name.IndexOf("@");
    var currentUsername = User.Identity.Name.Substring(0, indexOfAt);
}

<br />
<br />
<div class="container-fluid custom-form">
    <h2 class="heading-centered">@ViewBag.Title</h2>
    <hr />

    @using (Html.BeginForm("Edit", "Users", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
        @Html.AntiForgeryToken()
        <div class="row">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="control-label col-sm-offset-3 col-sm-2">@Html.DisplayNameFor(model => model.FirstName)</label>
                <div class="col-sm-3">
                    <input type="text" name="FirstName" value="@Model.FirstName" class="form-control" />

                    @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-offset-3 col-sm-2">@Html.DisplayNameFor(model => model.LastName)</label>
                <div class="col-sm-3">
                    <input type="text" name="LastName" value="@Model.LastName" class="form-control" />
                    @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-5 col-sm-6">
                    @Html.ActionLink("Back to profile page", "ProfilePage", new { username = currentUsername }, new { @class = "btn btn-default" })
                    <input type="submit" value="Edit" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

</div>

LearningCenter.App/Views/Users/ProfilePage.cshtml
@using LearningCenter.Models.ViewModels.User
@using Microsoft.AspNet.Identity
@model ProfileViewModel
@{
    ViewBag.Title = "Profile";
    var indexOfAt = User.Identity.Name.IndexOf("@");
    var currentUsername = User.Identity.Name.Substring(0, indexOfAt);
}

<br />
<br />
<div class="container custom-form">
    <div class="row">
        <div class="col-sm-12">
            <h2 class="heading-centered">Profile Information</h2>
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-sm-offset-2 col-sm-2">
            <h3><label class="label label-info">@Html.DisplayNameFor(model => model.Email)</label></h3>
        </div>
        <div class="col-sm-6">
            <h3>@Html.DisplayFor(m => m.Email, new { @class = "form-control" })</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-offset-2 col-sm-2">
            <h3><label class="label label-info">@Html.DisplayNameFor(model => model.FirstName)</label></h3>
        </div>
        <div class="col-sm-6">
            <h3>@Html.DisplayFor(m => m.FirstName, new { @class = "form-control" })</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-offset-2 col-sm-2">
            <h3><label class="label label-info">@Html.DisplayNameFor(model => model.LastName)</label></h3>
        </div>
        <div class="col-sm-6">
            <h3>@Html.DisplayFor(m => m.LastName, new { @class = "form-control" })</h3>
        </div>
    </div>
    @if (Model.Email == User.Identity.GetUserName())
    {
        <div class="row">
            <div class="col-sm-2 col-sm-offset-8">
                @Html.ActionLink("Edit profile", "Edit", new { username = currentUsername }, new { @class = "btn btn-block btn-warning" })
            </div>
            <div class="col-sm-2">
                @Html.ActionLink("Change password", "ChangePassword", "Manage", null, new { @class = "btn btn-block btn-info" })
                <br />
            </div>
        </div>
    }
</div>
<br />


<div class="col-sm-offset-1 col-sm-10">
    <ul class="nav nav-tabs">
        <li class="">
            <a href="#EnrolledCourses" data-toggle="tab" aria-expanded="true">@Html.DisplayNameFor(model => model.EnrolledCourses)</a>
        </li>
        <li class="">
            <a href="#ForumTopics" data-toggle="tab" aria-expanded="false">@Html.DisplayNameFor(model => model.ForumTopics)</a>
        </li>
        <li class="">
            <a href="#Grades" data-toggle="tab" aria-expanded="false">@Html.DisplayNameFor(model => model.QuizResults)</a>
        </li>
    </ul>
</div>

<div class="tab-content">
    <div class="tab-pane fade active" id="EnrolledCourses">
        <div class="col-sm-offset-1 col-sm-10">
            @Html.Partial("_DisplayCourses", Model.EnrolledCourses)
        </div>
    </div>
    <div class="tab-pane fade" id="ForumTopics">
        <div class="col-sm-offset-1 col-sm-10">
            @Html.Partial("_DisplayTopics", Model.ForumTopics)
        </div>
    </div>
    <div class="tab-pane fade active" id="Grades">
        <div class="col-sm-offset-1 col-sm-10">
            @Html.Partial("_DisplayGrades", Model.QuizResults)
        </div>
    </div>
</div>

LearningCenter.App/Views/Users/_DisplayCourses.cshtml
@using LearningCenter.Models.ViewModels.Course
@model IEnumerable<AllCourseViewModel>

@foreach (var course in Model)
{
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">@Html.ActionLink(course.Title, "Detailed", "Courses", new {area="Courses", id = course.Id }, null)</h3>
        </div>
        <div class="panel-body">
            <p>
                <span>@course.ShortDescription</span>
            </p>
        </div>
        <div class="panel-footer">
            <p>Students in course: @course.StudentsInCourse</p>
        </div>
    </div>
}

LearningCenter.App/Views/Users/_DisplayGrades.cshtml
@using LearningCenter.Models.ViewModels.Course
@model IEnumerable<GradeViewModel>
    
@foreach (var grade in Model)
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>@Html.ActionLink("Course: " + grade.CourseTitle, "Detailed", "Courses", new { area = "Courses", id = grade.CourseId }, null)</h3>
        </div>
        <div class="panel-body">
            <h4>Quiz Title: @grade.QuizTitle</h4>
            <h4>Result: @grade.Result / 10</h4>
        </div>
    </div>
}

LearningCenter.App/Views/Users/_DisplayTopics.cshtml
@using LearningCenter.Models.ViewModels.Forum
@model IEnumerable<AllTopicsViewModel>
    
@foreach (var topic in Model)
{
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">@Html.ActionLink(topic.Title, "Detailed", "Forum", new {area="Forum", id = topic.Id }, null)</h3>
        </div>
        <div class="panel-body">
            <h4>
                <span>By: @topic.Author</span>
            </h4>
            <h4>
                Tags: @foreach (string tag in topic.Tags)
                      {
                          @Html.DisplayFor(model => tag)<span> </span>
                      }
            </h4>
            <h4>
                <span>Published on: @topic.PublishDate.Date</span>
            </h4>
        </div>
        <div class="panel-footer">
            <p>Replies: @topic.Replies</p>
        </div>
    </div>
}